apiVersion: apps/v1
kind: Deployment
metadata:
 name: app-deployment 
spec:
  selector: 
    matchLabels:
      app: app-deployment
 replicas: 3
 template:
   metadata:
     labels:
       app: app-deployment
   spec:
    containers:
       - name: app-deployment
         image: ialokkr/native_poc:1.0
         ports:
            - containerPort: 80