---
- hosts: all
  become: yes
  tasks:
   - name: Installing git
     apt:
        name: git
        state: present
        update-cache: yes
   - name: installing apache2
     apt:
        name: apache2
        state: present
        status: restarted
        